server:
  port: 8081

resilience4j.retry:
  configs:
    default:
      maxAttempts: 5
      waitDuration: 1000
      retryExceptions:
        - java.lang.Exception
#  instances:
#    order-service:
#      baseConfig: default

